version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - /home/vit/work/bb:/usr/www/bb
      - /home/vit/work/cc:/usr/www/cc
    ports:
      - "80:80"
      # - "443:443"
    logging:
      options:
        max-size: 10m
